name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Node Binaries
        uses: actions/cache@v4
        with:
          path: cache/node-binaries
          key: node-binaries-v22.14.0-${{ runner.os }}
          restore-keys: |
            node-binaries-v22.14.0-

      - name: Install dependencies
        run: npm install

      - name: Build all platforms
        run: npm run build

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            binaries/methodalgo-macos-arm64
            binaries/methodalgo-macos-x64
            binaries/methodalgo-win-x64.exe
            binaries/methodalgo-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}